MINOR: Replace deprectated 'TIMESTAMPTOSTRING' with 'FORMAT_TIMESTAMP'
confluentinc/kafka-tutorials pull request #1341
Opened 2022-08-04 20:16 UTC by bbejeck

Updated insert statements to use 'UNIX_TIMESTAMP()' to generate dates

This PR proposes to solve the "too old" date issue by using `UNIX_TIMESTAMP()` to generate dates for inserting the initial data for the tutorial.  

### Description

### Staging Docs

### New tutorial checklist

2022-08-04 20:23 UTC, bbejeck commented on _includes/tutorials/session-windows/ksql/code/tutorial-steps/dev/populate-stream.sql
> +INSERT INTO clicks (ip, timestamp, url) VALUES ('51.56.119.117',FORMAT_TIMESTAMP(FROM_UNIXTIME(UNIX_TIMESTAMP() + (60 * 1000)),'yyyy-MM-dd''T''HH:mm:ssX'),'/nullam/orci/pede/venenatis.json');
The tutorial needs timestamps at different intervals to create sessions.  The idea is to add time in milliseconds to the current time - here the format is `Seconds * 1000`

2022-08-04 20:23 UTC, bbejeck commented on _includes/tutorials/session-windows/ksql/code/tutorial-steps/dev/populate-stream.sql
> +INSERT INTO clicks (ip, timestamp, url) VALUES ('53.170.33.192',FORMAT_TIMESTAMP(FROM_UNIXTIME(UNIX_TIMESTAMP() + (2 * 60 * 1000)),'yyyy-MM-dd''T''HH:mm:ssX'),'/vestibulum/vestibulum/ante/ipsum/primi
(Minutes * Sixty Seconds * 1000)

2022-08-04 20:33 UTC, davetroiano requested changes
Should we do anything about stale dates with the `ksql-test-runner`? i.e., this part [here](https://developer.confluent.io/tutorials/create-session-windows/ksql.html#test-it)

I ran into this [here](https://github.com/confluentinc/kafka-tutorials/pull/1340)

Maybe the compromise is to let the `ksql-test-runner` / "Test it" section have stale dates (maybe update them to be August 2022 rather than July 2019 as part of this, but leave them hard coded?), but also add infinite retention to topics [here](https://github.com/confluentinc/kafka-tutorials/pull/1340) to prevent race condition build failures due to topic cleanup due to default retention period not being large enough.

2022-08-04 22:26 UTC, davetroiano commented
oops I missed this:
>NOTE There's one issue remaining - the test data relies on hardcoded dates in a JSON file, so the tests for this PR will fail until we develop approach for creating test data

How about:
1. update the "dev" queries and expected outputs to not select timestamp / window boundaries
2. update the "test" input / output timestamps to be hardcoded but recent
3. add infinite retention so that we're safe against race condition build failures

That would get us to a happy place of improved quality and reliable build, right?

2022-09-12 21:48 UTC, bbejeck commented
@davetroiano  - PR updated 

>Should we do anything about stale dates with the ksql-test-runner? i.e., this part [here](https://developer.confluent.io/tutorials/create-session-windows/ksql.html#test-it)

After spending a good deal of time on this, I think we should leave the dates for the test runner alone because updating requires a lot of manual work for little-to-no gain.

The timestamps used in the tutorial are set to use the current time so it should always work as expected for users working through the tutorial

2022-09-13 13:41 UTC, bbejeck commented
Only one test failure and it's unrelated

Test for this PR passed https://confluentinc.semaphoreci.com/jobs/d8c26926-d73d-4f55-acfe-0feb12b2628f

2022-09-13 13:41 UTC, davetroiano approved these changes
LGTM! just remove the dummy comment before merging

2022-09-13 13:41 UTC, davetroiano commented on settings.gradle
> +// Dummy comment to force build
remove

2022-09-13 13:42 UTC, davetroiano commented
>After spending a good deal of time on this, I think we should leave the dates for the test runner alone because updating requires a lot of manual work for little-to-no gain.

@bbejeck sounds good, I agree

2022-09-13 13:42 UTC, bbejeck commented on settings.gradle
> +// Dummy comment to force build
ah yeah good catch

2022-09-13 13:58 UTC, bbejeck commented
latest change unrelated to files for the tutorial so merging now

2022-09-13 13:58 UTC, merged

2022-09-13 13:58 UTC, bbejeck commented
Thanks for the review @davetroiano!