MINOR [WIP]: Update KT index page
confluentinc/kafka-tutorials pull request #683
Opened 2021-01-11 16:27 UTC by bbejeck

### Description

PR for adding proposed changes to KT index page

### Staging Docs

http://kafka-tutorials-staging.s3-website-us-west-2.amazonaws.com/MINOR_update_index_page_layout

2021-01-11 16:49 UTC, bbejeck commented
This is an initial PR for breaking up the `Apply a function to data`.  It will be updated soon to incorporate the changes proposed in #575

2021-01-28 13:05 UTC, ybyzek reviewed
@bbejeck this looks so much better, love it!

Some suggested tweaks:

1. Some cards have a period, some do not.  They should all be consistent
2. My leaning is that 3 cards wide looks better than 4 cards wide -- but this is very subjective and you can ignore if you prefer 4
3. How about instead of `Create X windows`, simplify to `X windows`?
4. Does `Find distinct events` belong in `Routing Events`, or is there a better card for it?

2021-01-28 15:58 UTC, colinhicks commented
> My leaning is that 3 cards wide looks better than 4 cards wide -- but this is very subjective and you can ignore if you prefer 4

A related consideration is that the CSS is written with 3 cards in mind. As implemented, the 4-card layout appears to work at viewport width of ~1450px and above. Between 1080px and 1450px, the outer card content is cut off. 

It would be possible to use breakpoints to switch between 3 and 4 cards depending on browser widths, but this would require some changes to the styles and markup. If part of the goal is optimization for screen widths > ~1450, this effort is probably reasonable overall. If not, I suggest sticking with 3 cards.

2021-01-28 19:09 UTC, bbejeck commented
Updates

1. Only 3 cards per row
2. Shortened titles to fit on one line, no-breaks
3. Address comments from @ybyzek https://github.com/confluentinc/kafka-tutorials/pull/683#pullrequestreview-578311188

2021-01-28 20:35 UTC, ybyzek commented on index.html
> +            <li><a href="ccloud-produce-consume/kafka.html">Using Confluent Cloud</a></li>
```suggestion
            <li><a href="ccloud-produce-consume/kafka.html">Using Confluent Cloud CLI</a></li>
```

2021-01-28 20:39 UTC, ybyzek commented
@bbejeck please note https://github.com/confluentinc/kafka-tutorials/pull/697 should be reviewed/merged into this PR before merging (it fixes the resolution of the new images)

Also, looks like this tutorial is missing https://kafka-tutorials.confluent.io/message-ordering/kafka.html .  I compared `release` to this PR, and it looks like it's only one off, so hopefully this is the only missing one:

```
grep html index.html | grep li | wc -l 
```

2021-01-28 20:45 UTC, ybyzek requested changes
Marking note on required change but overall looks really good :)

2021-01-29 01:10 UTC, ybyzek approved these changes
@bbejeck 🥳 LGTM

2021-01-29 01:10 UTC, bbejeck commented
Updated for comments.

I took a stab at setting the max height of the card and adding scrolling.  Check out the `Manipulating Streams` card as that has overflow content. 

\cc @colinhicks for CSS changes

2021-01-29 01:13 UTC, bbejeck commented
I think we need a way to make it obvious when users need to scroll.

Ideas anyone?  \cc @colinhicks

2021-01-29 01:14 UTC, ybyzek commented
@bbejeck sorry, missed this in my last review, I think latest commit is still missing:

```
          <li><a href="message-ordering/kafka.html">Idempotent producer for message ordering and no duplication</a></li>		
```

Once that is added, LGTM.

2021-01-29 01:18 UTC, bbejeck commented
@ybyzek it's there I didn't use the correct link text - updating now

2021-01-29 01:25 UTC, ybyzek commented
Thank you @bbejeck ! 👍

2021-01-29 01:45 UTC, merged

2021-01-29 01:46 UTC, bbejeck commented
Thanks for the reviews @ybyzek and @colinhicks !